### ISSUE TITLE
Issue with running the addon with UI Tests and UI Review disabled

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/addon-visual-tests#230]
From AP-3682

During some testing, I noticed that running the addon with the settings we currently provide to our customers (i.e., UI review and UI testing)  disabled can lead to misconceptions from our users despite our best efforts to provide the necessary mechanisms and UX to match their expectations.

The most critical point is when a customer, for any reason above our control, disables UI Review and UI Tests, runs Storybook with the addon configured, and tries to run tests on their components, which leaves it in an inconsistent and incorrect state as the setting is disabled in their project. 

For more context, see the discussion linked in the Linear ticket (i.e, AP-3682)

Looking forward to hearing everyone's thoughts on this so we can have a clear path moving forward.

**Comment by MichaelArestad** [comment]
There are a few more comments in the original ticket, but this is the key one:

### Proposal

* Show an error message when UI Tests are disabled in Chromatic.
* Allow user to re-enable UI Tests from the addon
  * Fallback: Link to the manage screen on chromatic.com so that the user can re-enable UI Tests there.

We'd need to create an error message for this scenario and then apply our existing template. The turnaround can be quite fast. Design 👇

![image](https://github.com/chromaui/addon-visual-tests/assets/1123119/b20b83af-4852-407b-9e1d-6c7e28823088)

We will send them to the web app to reenable tests.
